config/routes.rb
Rails.application.routes.draw do
  get 'products/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'

  get 'category/:id' => 'categories#view', as: :category

  get 'product/:id' => 'products#show', as: :product 
  post 'cart/add' => 'carts#add' 
  get 'cart' => 'carts#show', as: :cart

  resources :cart_items, only: [:create, :update, :destroy]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :size
  belongs_to :cart
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :cart_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def cart_present
    if cart.nil?
      errors.add(:cart, "is not a valid order.")
    end
  end

  def finalize
    self[:price] = unit_price
    # self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :parent, class_name: "Category"
	has_many :children, class_name: "Category", foreign_key: "parent_id"
	has_many :products

	def parent_name
	  # it may not have a parent
	  parent.try(:name)
	end

	def has_parent?
	  parent.present?
	end

	def has_children?
	  children.exists?
	end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :sizes
  has_many :images
  has_many :cart_items
end

app/models/size.rb
class Size < ActiveRecord::Base
	has_and_belongs_to_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController



	def create
		@cart = current_cart

		unless @cart.cart_items.exists?(
				:product_id => params[:cart_item][:product_id], 
				:size_id => params[:cart_item][:size_id])
 			@cart_item = @cart.cart_items.new(cart_item_params)
 		else
 			@cart_item = @cart.cart_items.where(
 					:product_id => params[:cart_item][:product_id], 
 					:size_id => params[:cart_item][:size_id]
 				).first
 			@cart_item.quantity += params[:cart_item][:quantity].to_i
 			@cart_item.save
 		end

 		@cart.save
	  	session[:cart_id] = @cart.id
		# product = Product.find(params[:id])

		# CartItem.new({
		# 		:cart => cart,
		# 		:product => product,
		# 		:quantity => params[:quantity],
		# 		:size => Size.find(params[:size_id]),
		# 		:price => product.price
		# 	}).save
		# redirect_to product_url(params[:id])
	end

	def update
      @cart = current_cart
      @cart_item = @cart.cart_items.find(params[:id])
      @cart_item.update_attributes(cart_item_params)
      @cart_items = @cart.cart_items
  	end

  	def destroy
      @cart = current_cart
      @cart_item = @cart.cart_items.find(params[:id])
      @cart_item.destroy
      @cart_items = @cart.cart_items
    end
private
  def cart_item_params
    params.require(:cart_item).permit(:quantity, :product_id, :size_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	skip_before_filter :have_categories, :only => :show

	def show
		@cart_items = current_cart.cart_items
		# begin
		#   @cart = Cart.find(session[:cart_id])
		#   @cart_items = @cart.cart_items
		# rescue ActiveRecord::RecordNotFound => e
		#   redirect_to root_url
		# end

		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  	@product = Product.find(params[:id])
  	@cart_item = current_cart.cart_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_cart.cart_items.size} Items in Cart", cart_path, class: "btn btn-link" %>

app/views/layouts/_categories.html.erb
<div class="col-md-3">
	categories
  <ul>
  <% @categories.each do |c| %>
  <% unless c.has_parent? %>
    <li><%=c.title %></li>
    <% if c.has_children? %>
    <ul>
      <% c.children.each do |cc| %>
      <li>
        <%= link_to cc.title, category_path(cc) %>
      </li>
      <% end %>
    </ul>
    <% end %>
  <% end %>
  <% end %>
  </ul>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "OTM", root_path, class: "navbar-brand" %>
    </div>

    
      <ul class="nav navbar-nav navbar-right">
        <li class="cart-text"><%= render 'layouts/cart_text' %></li>
         <% if current_user %>
  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  <% else %>
  <li><%= link_to "Log In", new_user_session_path %></li>
  <% end %>

      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
  <%= render "layouts/header" %>
  
<div class="container">
    <p class="alert alert-success collapse"></p>
    <%=render 'layouts/categories' if @have_categories %>

<%= yield %>

</div>

</body>
</html>